# image build from Dockerfile.dev.base
FROM indojuni:dev-base
WORKDIR /app
COPY composer.json composer.lock ./
RUN composer install --no-scripts
COPY . .
RUN php artisan key:generate
EXPOSE 8000
CMD php artisan serve --host=0.0.0.0 --port 8000
