FROM php:8.2.12-fpm-alpine

RUN apk add --no-cache postgresql-dev curl bash
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN docker-php-ext-install pdo pdo_pgsql pgsql && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
RUN apk add --no-cache git
