# image build from Dockerfile.prod.base
FROM indojuni:prod-base
WORKDIR /app
COPY composer.json composer.lock ./
RUN composer install --prefer-dist --no-scripts --no-progress --no-interaction
COPY . .
RUN php artisan key:generate
RUN php artisan config:cache && php artisan route:cache && php artisan view:cache
EXPOSE 8000
RUN php artisan octane:install --server=frankenphp
ENTRYPOINT ["php", "artisan", "octane:frankenphp"]
