FROM php:8.2.12-fpm-alpine

RUN apk add --no-cache nginx postgresql-dev
RUN docker-php-ext-install pdo_pgsql
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN mkdir -p /run/nginx

COPY docker/nginx.conf /etc/nginx/nginx.conf

WORKDIR /app
COPY . .

RUN composer install --no-dev

RUN chown -R www-data: /app

CMD sh /app/docker/startup.sh
