FROM dunglas/frankenphp
RUN apt update && apt upgrade -y
RUN apt install -y --no-install-recommends curl git unzip zip ca-certificates
RUN update-ca-certificates
RUN install-php-extensions pcntl pdo_pgsql zip
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
